/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SysAdmin;

import Model.CriminalJusticeSystem.CriminalJusticeSystem;
import Model.DB4OUtil.DB4OUtil;
import Model.Employee.Employee;
import Model.Location;
import Model.PrisonEcosystem;
import Model.Role.CriminalJusticeSystemAdmin;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thejas G R
 */
public class ManageJudicialSystem extends javax.swing.JPanel {

    /**
     * Creates new form ManageJudicialSystem
     */
    JPanel container;
    PrisonEcosystem system;
    CriminalJusticeSystem selectedJudicialSystem;

    public ManageJudicialSystem(JPanel container, PrisonEcosystem system) {
        initComponents();
        this.container = container;
        this.system = system;
        initializeTable();
        tblJudicialSytemAdmin.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                initializeFields();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

            private void initializeFields() {
                selectedJudicialSystem = (CriminalJusticeSystem) tblJudicialSytemAdmin.getModel().getValueAt(tblJudicialSytemAdmin.getSelectedRow(), 0);
                txtJudicialSystemName.setText(selectedJudicialSystem.getName());
                txtJudicialSystemLocation.setText(String.valueOf(selectedJudicialSystem.getLocation()));
                txtJudicialSystemAdminPassword.setText(selectedJudicialSystem.getAdmin().getUserAccount().getPassword());
                txtJudicialSystemAdminUsername.setText(selectedJudicialSystem.getAdmin().getUserAccount().getUsername());
                txtJudicialSystemAdminName.setText(selectedJudicialSystem.getAdmin().getName());
                drpdwnStatus.setSelectedIndex(selectedJudicialSystem.getStatus() == true ? 0 : 1);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJudicialSytemAdmin = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblJudicialSystemName = new javax.swing.JLabel();
        txtJudicialSystemName = new javax.swing.JTextField();
        lblJudicialSystemLocation = new javax.swing.JLabel();
        txtJudicialSystemLocation = new javax.swing.JTextField();
        drpdwnStatus = new javax.swing.JComboBox<>();
        lblJudicialSystemStatus = new javax.swing.JLabel();
        lblJudicialSystemAdminUsername = new javax.swing.JLabel();
        lblJudicialSystemAdminPassword = new javax.swing.JLabel();
        lblJudicialSystemAdminName = new javax.swing.JLabel();
        txtJudicialSystemAdminUsername = new javax.swing.JTextField();
        txtJudicialSystemAdminPassword = new javax.swing.JTextField();
        txtJudicialSystemAdminName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        addBtn1 = new javax.swing.JLabel();
        updateBtn1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblJudicialSytemAdmin.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tblJudicialSytemAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judicial System Name", "Admin Name", "Username", "Password", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblJudicialSytemAdmin);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 260));

        jPanel1.setBackground(new java.awt.Color(242, 248, 255));

        lblJudicialSystemName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudicialSystemName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudicialSystemName.setText("Judicial System Name");

        txtJudicialSystemName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblJudicialSystemLocation.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudicialSystemLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudicialSystemLocation.setText("Location");

        txtJudicialSystemLocation.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        drpdwnStatus.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        drpdwnStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Service", "Out of Service" }));

        lblJudicialSystemStatus.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudicialSystemStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudicialSystemStatus.setText("Status");

        lblJudicialSystemAdminUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudicialSystemAdminUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJudicialSystemAdminUsername.setText("Admin Username");

        lblJudicialSystemAdminPassword.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudicialSystemAdminPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudicialSystemAdminPassword.setText("Admin Password");

        lblJudicialSystemAdminName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudicialSystemAdminName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudicialSystemAdminName.setText("Admin Name");

        txtJudicialSystemAdminUsername.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtJudicialSystemAdminPassword.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtJudicialSystemAdminName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudicialSystemName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJudicialSystemLocation)
                    .addComponent(lblJudicialSystemStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJudicialSystemName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJudicialSystemLocation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drpdwnStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, 196, Short.MAX_VALUE))
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudicialSystemAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJudicialSystemAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJudicialSystemAdminUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJudicialSystemAdminPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(txtJudicialSystemAdminUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJudicialSystemAdminName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(lblJudicialSystemAdminUsername)
                                .addComponent(txtJudicialSystemAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(lblJudicialSystemAdminPassword)
                                .addComponent(txtJudicialSystemAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(txtJudicialSystemAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(lblJudicialSystemAdminName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblJudicialSystemName)
                            .addComponent(txtJudicialSystemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblJudicialSystemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJudicialSystemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblJudicialSystemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drpdwnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1000, 220));

        jPanel2.setBackground(new java.awt.Color(235, 242, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn1.setBackground(new java.awt.Color(120, 168, 255));
        addBtn1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        addBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn1.setText("Add");
        addBtn1.setOpaque(true);
        addBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtn1MouseClicked(evt);
            }
        });
        jPanel2.add(addBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        updateBtn1.setBackground(new java.awt.Color(120, 168, 255));
        updateBtn1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        updateBtn1.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateBtn1.setText("Update");
        updateBtn1.setMaximumSize(new java.awt.Dimension(47, 17));
        updateBtn1.setMinimumSize(new java.awt.Dimension(47, 17));
        updateBtn1.setOpaque(true);
        updateBtn1.setPreferredSize(new java.awt.Dimension(47, 17));
        updateBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtn1MouseClicked(evt);
            }
        });
        jPanel2.add(updateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1000, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtn1MouseClicked
        // TODO add your handling code here:

        if (checkInputFields(txtJudicialSystemLocation) && checkInputFields(txtJudicialSystemAdminName) && checkInputFields(txtJudicialSystemName) && checkInputFields(txtJudicialSystemAdminPassword) && checkInputFields(txtJudicialSystemAdminUsername)) {
//            if (system.getPrisons().checkIfUsernameIsUnique(txtJudicialSystemAdminName.getText())) {
//String[] locationData =  txtJudicialSystemLocation.getText().split(", ");
//CriminalJusticeSystem newCJS = new CriminalJusticeSystem(txtJudicialSystemName.getText(), new Location(Double.parseDouble(locationData[0]), Double.parseDouble(locationData[1])), drpdwnStatus.getSelectedIndex()==0);
           
        //Validations
        if(!checkInputFields(txtJudicialSystemLocation, "^[\\p{L} .'-]+$") || !checkInputFields(txtJudicialSystemAdminName, "^[\\p{L} .'-]+$") || !checkInputFields(txtJudicialSystemName, "^[\\p{L} .'-]+$")
                    || !checkInputFields(txtJudicialSystemAdminPassword, "^[\\p{L} .'-]+$") || !checkInputFields(txtJudicialSystemAdminUsername, "^[\\p{L} .'-]+$")){
                JOptionPane.showMessageDialog(this, "Please enter valid Judicial System details");
                return;
            }

        if (checkIfCJSNameIsUnique()) {
                CriminalJusticeSystem newCriminalJusticeSystem = new CriminalJusticeSystem(txtJudicialSystemName.getText(), txtJudicialSystemLocation.getText(), true);
                Employee cjsAdmin = new Employee(system,txtJudicialSystemAdminName.getText(), txtJudicialSystemAdminUsername.getText(), txtJudicialSystemAdminPassword.getText(), newCriminalJusticeSystem, new CriminalJusticeSystemAdmin());
                newCriminalJusticeSystem.setAdmin(cjsAdmin);
                system.getCriminalJusticeSystems().add(newCriminalJusticeSystem);
                initializeTable();
                resetFields();
                JOptionPane.showMessageDialog(this, "New Criminal Justice System(CJS) has been added");
                DB4OUtil.storeSystem(system);
            } else {
                JOptionPane.showMessageDialog(this, "CJS name already exists, try a different name");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for adding a new CJS");
        }
        
    }//GEN-LAST:event_addBtn1MouseClicked

    private void updateBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtn1MouseClicked
        // TODO add your handling code here:

        if (checkInputFields(txtJudicialSystemLocation) && checkInputFields(txtJudicialSystemAdminName) && checkInputFields(txtJudicialSystemName) && checkInputFields(txtJudicialSystemAdminPassword) && checkInputFields(txtJudicialSystemAdminUsername)) {
            if (selectedJudicialSystem != null) {
                //Validations
                if(!checkInputFields(txtJudicialSystemLocation, "^[\\p{L} .'-]+$") || !checkInputFields(txtJudicialSystemAdminName, "^[\\p{L} .'-]+$") || !checkInputFields(txtJudicialSystemName, "^[\\p{L} .'-]+$")
                    || !checkInputFields(txtJudicialSystemAdminPassword, "^[\\p{L} .'-]+$") || !checkInputFields(txtJudicialSystemAdminUsername, "^[\\p{L} .'-]+$")){
                JOptionPane.showMessageDialog(this, "Please enter valid Judicial System details before updating");
                return;
            }
                for (CriminalJusticeSystem cjs : system.getCriminalJusticeSystems()) {
                    if (selectedJudicialSystem.getName().equals(cjs.getName())) {
                        //                        String[] locationData =  txtJudicialSystemLocation.getText().split(", ");
                        cjs.setName(txtJudicialSystemName.getText());
                        //                         cjs.setLocation(new Location(Double.parseDouble(locationData[0]), Double.parseDouble(locationData[1])));
                        cjs.setLocation(txtJudicialSystemLocation.getText());
                        cjs.getAdmin().getUserAccount().setUsername(txtJudicialSystemAdminUsername.getText());
                        cjs.getAdmin().getUserAccount().setPassword(txtJudicialSystemAdminPassword.getText());
                        cjs.getAdmin().setName(txtJudicialSystemAdminName.getText());
                        cjs.setStatus(drpdwnStatus.getSelectedIndex() == 0);
                        initializeTable();
                        resetFields();
                        JOptionPane.showMessageDialog(this, "Criminal Justice System details updated successfully");
                        DB4OUtil.storeSystem(system);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a criminal justice system to update from the table");
            }
        }
    }//GEN-LAST:event_updateBtn1MouseClicked
    private void initializeTable() {
        ArrayList<CriminalJusticeSystem> cjsDetials = system.getCriminalJusticeSystems();
        DefaultTableModel tablemodel = (DefaultTableModel) tblJudicialSytemAdmin.getModel();
        tablemodel.setRowCount(0);
        if (cjsDetials != null) {
            for (CriminalJusticeSystem cjs : cjsDetials) {
                if (cjs != null) {
                    Object[] row = new Object[6];
                    row[0] = cjs;
                    row[1] = cjs.getAdmin().getName();
                    row[2] = cjs.getAdmin().getUserAccount().getUsername();
                    row[3] = cjs.getAdmin().getUserAccount().getPassword();
                    row[4] = String.valueOf(cjs.getLocation());
                    row[5] = cjs.getStatus() == true ? "In service"
                            : "Out of service";
                    tablemodel.addRow(row);
                }
            }
        }
    }

    public boolean checkInputFields(javax.swing.JTextField txtField, String regex) {
        return txtField.getText() != null && !txtField.getText().isEmpty() && txtField.getText().matches(regex);
    }

    public boolean checkInputFields(javax.swing.JTextField txtField) {
        return txtField.getText() != null && !txtField.getText().isEmpty();
    }

    private void resetFields() {
        txtJudicialSystemLocation.setText("");
        txtJudicialSystemName.setText("");
        txtJudicialSystemAdminPassword.setText("");
        txtJudicialSystemAdminUsername.setText("");
        txtJudicialSystemAdminName.setText("");
        drpdwnStatus.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn1;
    private javax.swing.JComboBox<String> drpdwnStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudicialSystemAdminName;
    private javax.swing.JLabel lblJudicialSystemAdminPassword;
    private javax.swing.JLabel lblJudicialSystemAdminUsername;
    private javax.swing.JLabel lblJudicialSystemLocation;
    private javax.swing.JLabel lblJudicialSystemName;
    private javax.swing.JLabel lblJudicialSystemStatus;
    private javax.swing.JTable tblJudicialSytemAdmin;
    private javax.swing.JTextField txtJudicialSystemAdminName;
    private javax.swing.JTextField txtJudicialSystemAdminPassword;
    private javax.swing.JTextField txtJudicialSystemAdminUsername;
    private javax.swing.JTextField txtJudicialSystemLocation;
    private javax.swing.JTextField txtJudicialSystemName;
    private javax.swing.JLabel updateBtn1;
    // End of variables declaration//GEN-END:variables

    private boolean checkIfCJSNameIsUnique() {
        if (checkInputFields(txtJudicialSystemName)) {
            for (CriminalJusticeSystem criminalJusticeSystem : system.getCriminalJusticeSystems()) {
                if (criminalJusticeSystem.getName().equals(txtJudicialSystemName.getText())) {
                    return false;
                }
            }
        }
        return true;
    }
}
