/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SysAdmin;

import Model.DB4OUtil.DB4OUtil;
import Model.Employee.Employee;
import Model.Hospital.Hospital;
import Model.Hospital.Management;
import Model.Location;
import Model.PrisonEcosystem;
import Model.Role.HospitalAdmin;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thejas
 */
public class ManageHospitals extends javax.swing.JPanel {

    JPanel container;
    PrisonEcosystem system;
    Hospital selectedHospital;

    /**
     * Creates new form ManageHospitals
     *
     * @param container
     */
    public ManageHospitals(JPanel container, PrisonEcosystem system) {
        initComponents();
        this.container = container;
        this.system = system;
        initializeTable();
        tblHospitals.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                initializeFields();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

            private void initializeFields() {
                selectedHospital = (Hospital) tblHospitals.getModel().getValueAt(tblHospitals.getSelectedRow(), 0);
                txtHospitalName.setText(selectedHospital.getName());
                txtHospitalAdminName.setText(selectedHospital.getManagement().getHospitalAdmin().getName());
                txtHospitalLocation.setText(String.valueOf(selectedHospital.getLocation()));
                txtHospitalAdminPassword.setText(selectedHospital.getManagement().getHospitalAdmin().getUserAccount().getPassword());
                txtHospitalAdminUsername.setText(selectedHospital.getManagement().getHospitalAdmin().getUserAccount().getUsername());
                drpdwnStatus.setSelectedIndex(selectedHospital.getStatus() == true ? 0 : 1);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospitals = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblHospitalName = new javax.swing.JLabel();
        lblHospitalLocation = new javax.swing.JLabel();
        lblHospitalStatus = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtHospitalLocation = new javax.swing.JTextField();
        drpdwnStatus = new javax.swing.JComboBox<>();
        txtHospitalAdminUsername = new javax.swing.JTextField();
        lblHospitalAdminPassword = new javax.swing.JLabel();
        lblHospitalAdminName = new javax.swing.JLabel();
        txtHospitalAdminName = new javax.swing.JTextField();
        lblHospitalAdminUsername = new javax.swing.JLabel();
        txtHospitalAdminPassword = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        addBtn1 = new javax.swing.JLabel();
        updateBtn1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHospitals.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tblHospitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Admin Name", "Username", "Password", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHospitals);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 270));

        jPanel1.setBackground(new java.awt.Color(242, 248, 255));

        lblHospitalName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblHospitalName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospitalName.setText("Name");

        lblHospitalLocation.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblHospitalLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospitalLocation.setText("Location");

        lblHospitalStatus.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblHospitalStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospitalStatus.setText("Status");

        txtHospitalName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtHospitalLocation.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        drpdwnStatus.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        drpdwnStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Service", "Out of Service" }));

        txtHospitalAdminUsername.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblHospitalAdminPassword.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblHospitalAdminPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospitalAdminPassword.setText("Admin Password");

        lblHospitalAdminName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblHospitalAdminName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospitalAdminName.setText("Admin Name");

        txtHospitalAdminName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblHospitalAdminUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblHospitalAdminUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospitalAdminUsername.setText("Admin Username");

        txtHospitalAdminPassword.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospitalLocation)
                    .addComponent(lblHospitalStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHospitalName)
                    .addComponent(txtHospitalLocation)
                    .addComponent(drpdwnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHospitalAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospitalAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospitalAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHospitalAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospitalName)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHospitalAdminUsername)
                        .addComponent(txtHospitalAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtHospitalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospitalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHospitalAdminPassword)
                        .addComponent(txtHospitalAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(drpdwnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospitalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHospitalAdminName)
                        .addComponent(txtHospitalAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1000, 210));

        jPanel2.setBackground(new java.awt.Color(235, 242, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn1.setBackground(new java.awt.Color(120, 168, 255));
        addBtn1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        addBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn1.setText("Add");
        addBtn1.setOpaque(true);
        addBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtn1MouseClicked(evt);
            }
        });
        jPanel2.add(addBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        updateBtn1.setBackground(new java.awt.Color(120, 168, 255));
        updateBtn1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        updateBtn1.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateBtn1.setText("Update");
        updateBtn1.setMaximumSize(new java.awt.Dimension(47, 17));
        updateBtn1.setMinimumSize(new java.awt.Dimension(47, 17));
        updateBtn1.setOpaque(true);
        updateBtn1.setPreferredSize(new java.awt.Dimension(47, 17));
        updateBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtn1MouseClicked(evt);
            }
        });
        jPanel2.add(updateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1000, 50));
    }// </editor-fold>//GEN-END:initComponents
    private void initializeTable() {
        ArrayList<Hospital> hospitalDetails = system.getHospitals();
        DefaultTableModel tablemodel = (DefaultTableModel) tblHospitals.getModel();
        tablemodel.setRowCount(0);
        if (hospitalDetails != null) {
            for (Hospital hospital : hospitalDetails) {
                if (hospital != null) {
                    Object[] row = new Object[6];
                    row[0] = hospital;
                    row[1] = hospital.getManagement().getHospitalAdmin().getName();
                    row[2] = hospital.getManagement().getHospitalAdmin().getUserAccount().getUsername();
                    row[3] = hospital.getManagement().getHospitalAdmin().getUserAccount().getPassword();
                    row[4] = hospital.getLocation();
                    row[5] = hospital.getStatus() == true ? "In service": "Out of service";
                    tablemodel.addRow(row);
                }
            }
        }
    }

    private void resetFields() {
        txtHospitalAdminPassword.setText("");
        txtHospitalAdminUsername.setText("");
        txtHospitalLocation.setText("");
        txtHospitalName.setText("");
        txtHospitalAdminName.setText("");
        drpdwnStatus.setSelectedIndex(0);
    }
    private void addBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtn1MouseClicked
        // TODO add your handling code here:

        if (checkInputFields(txtHospitalName) && checkInputFields(txtHospitalAdminName) && checkInputFields(txtHospitalAdminUsername) && checkInputFields(txtHospitalAdminPassword) && checkInputFields(txtHospitalLocation)) {
              //Validations
        if(!checkInputFields(txtHospitalName, "^[\\p{L} .'-]+$") || !checkInputFields(txtHospitalAdminName, "^[\\p{L} .'-]+$") || !checkInputFields(txtHospitalAdminUsername, "^[\\p{L} .'-]+$")
                    || !checkInputFields(txtHospitalAdminPassword, "^[\\p{L} .'-]+$") || !checkInputFields(txtHospitalLocation, "^[\\p{L} .'-]+$")){
                JOptionPane.showMessageDialog(this, "Please enter valid Hospital details");
                return;
            }
		    if (checkIfHospitalNameIsUnique()) {
//                String[] locationData = txtHospitalLocation.getText().split(", ");
//Hospital newHospital = new Hospital(txtHospitalName.getText(), new Location(Double.parseDouble(locationData[0]), Double.parseDouble(locationData[1])), (drpdwnStatus.getSelectedIndex()==0));
                 Hospital newHospital = new Hospital(txtHospitalName.getText(), txtHospitalLocation.getText(), true);
                Employee hospitalAdmin = new Employee(system,txtHospitalAdminName.getText(), txtHospitalAdminUsername.getText(), txtHospitalAdminPassword.getText(), newHospital, new HospitalAdmin());
                newHospital.getManagement().setHospitalAdmin(hospitalAdmin);
                system.getHospitals().add(newHospital);
                initializeTable();
                resetFields();
                JOptionPane.showMessageDialog(this, "New Hospital has been added");
            } else {
                JOptionPane.showMessageDialog(this, "Hospital name already exists, try a different name");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for adding a new Hospital");
        }

    }//GEN-LAST:event_addBtn1MouseClicked

    private void updateBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtn1MouseClicked
        // TODO add your handling code here:

        if (checkInputFields(txtHospitalName) && checkInputFields(txtHospitalAdminName) && checkInputFields(txtHospitalAdminUsername) && checkInputFields(txtHospitalAdminPassword) && checkInputFields(txtHospitalLocation)) {
            if (selectedHospital != null) {
                //Validations
                if(checkInputFields(txtHospitalName, "^[\\p{L} .'-]+$") || !checkInputFields(txtHospitalAdminName, "^[\\p{L} .'-]+$") || !checkInputFields(txtHospitalAdminUsername, "^[\\p{L} .'-]+$")
                    || !checkInputFields(txtHospitalAdminPassword, "^[\\p{L} .'-]+$") || !checkInputFields(txtHospitalLocation, "^[\\p{L} .'-]+$")){
                JOptionPane.showMessageDialog(this, "Please enter valid Hospital details before updating");
                return;
            }
                for (Hospital hospital : system.getHospitals()) {
                    if (selectedHospital.getName().equals(hospital.getName())) {
                        //String[] locationData =  txtHospitalLocation.getText().split(", ");
                        hospital.setName(txtHospitalName.getText());
                        // hospital.setLocation(new Location(Double.parseDouble(locationData[0]), Double.parseDouble(locationData[1])));
                        hospital.setLocation(txtHospitalLocation.getText());
                        hospital.getManagement().getHospitalAdmin().getUserAccount().setUsername(txtHospitalAdminUsername.getText());
                        hospital.getManagement().getHospitalAdmin().getUserAccount().setPassword(txtHospitalAdminPassword.getText());
                        hospital.getManagement().getHospitalAdmin().setName(txtHospitalAdminName.getText());
                        hospital.setStatus(drpdwnStatus.getSelectedIndex() == 0);
                        initializeTable();
                        resetFields();
                        JOptionPane.showMessageDialog(this, "Hospital details updated successfully");
                        DB4OUtil.storeSystem(system);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a hospital to update from the table");
            }
        }
    }//GEN-LAST:event_updateBtn1MouseClicked
    public boolean checkInputFields(javax.swing.JTextField txtField, String regex) {
        return txtField.getText() != null && !txtField.getText().isEmpty() && txtField.getText().matches(regex);
    }

    public boolean checkInputFields(javax.swing.JTextField txtField) {
        return txtField.getText() != null && !txtField.getText().isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn1;
    private javax.swing.JComboBox<String> drpdwnStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHospitalAdminName;
    private javax.swing.JLabel lblHospitalAdminPassword;
    private javax.swing.JLabel lblHospitalAdminUsername;
    private javax.swing.JLabel lblHospitalLocation;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblHospitalStatus;
    private javax.swing.JTable tblHospitals;
    private javax.swing.JTextField txtHospitalAdminName;
    private javax.swing.JTextField txtHospitalAdminPassword;
    private javax.swing.JTextField txtHospitalAdminUsername;
    private javax.swing.JTextField txtHospitalLocation;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JLabel updateBtn1;
    // End of variables declaration//GEN-END:variables

    private boolean checkIfHospitalNameIsUnique() {
        if (checkInputFields(txtHospitalName)) {
            for (Hospital hospital : system.getHospitals()) {
                if (hospital.getName().equals(txtHospitalName.getText())) {
                    return false;
                }
            }
        }
        return true;
    }
}
