/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SysAdmin;

import Model.DB4OUtil.DB4OUtil;
import Model.Employee.Employee;
import Model.FoodCateringService.FoodCateringService;
import Model.Location;
import Model.PrisonEcosystem;
import Model.Role.FoodCateringServiceAdmin;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thejas
 */
public class ManageCaterers extends javax.swing.JPanel {

    JPanel container;
    PrisonEcosystem system;
    FoodCateringService selectedCateringService;

    /**
     * Creates new form ManageCaterers
     *
     * @param container
     * @param system
     */
    public ManageCaterers(JPanel container, PrisonEcosystem system) {
        initComponents();
        this.container = container;
        this.system = system;
        initializeTable();
        tblCaterers.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                initializeFields();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

            private void initializeFields() {
                selectedCateringService = (FoodCateringService) tblCaterers.getModel().getValueAt(tblCaterers.getSelectedRow(), 0);
                txtCatererName.setText(selectedCateringService.getName());
                txtCatererLocation.setText(String.valueOf(selectedCateringService.getLocation()));
                txtCatererAdminPassword.setText(selectedCateringService.getManagement().getAdmin().getUserAccount().getPassword());
                txtCatererAdminUsername.setText(selectedCateringService.getManagement().getAdmin().getUserAccount().getUsername());
                txtCatererAdminName.setText(selectedCateringService.getManagement().getAdmin().getName());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCaterers = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        addBtn1 = new javax.swing.JLabel();
        updateBtn1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCatererName = new javax.swing.JLabel();
        txtCatererName = new javax.swing.JTextField();
        lblCatererLocation = new javax.swing.JLabel();
        txtCatererLocation = new javax.swing.JTextField();
        lblCatererLocation1 = new javax.swing.JLabel();
        drpdwnStatus = new javax.swing.JComboBox<>();
        lblCatererAdminUsername = new javax.swing.JLabel();
        lblCatererAdminPassword = new javax.swing.JLabel();
        lblCatererAdminName = new javax.swing.JLabel();
        txtCatererAdminUsername = new javax.swing.JTextField();
        txtCatererAdminPassword = new javax.swing.JTextField();
        txtCatererAdminName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCaterers.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tblCaterers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caterer Name", "Admin Name", "Username", "Password", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCaterers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 275));

        jPanel2.setBackground(new java.awt.Color(235, 242, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn1.setBackground(new java.awt.Color(120, 168, 255));
        addBtn1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        addBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn1.setText("Add");
        addBtn1.setOpaque(true);
        addBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtn1MouseClicked(evt);
            }
        });
        jPanel2.add(addBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        updateBtn1.setBackground(new java.awt.Color(120, 168, 255));
        updateBtn1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        updateBtn1.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateBtn1.setText("Update");
        updateBtn1.setMaximumSize(new java.awt.Dimension(47, 17));
        updateBtn1.setMinimumSize(new java.awt.Dimension(47, 17));
        updateBtn1.setOpaque(true);
        updateBtn1.setPreferredSize(new java.awt.Dimension(47, 17));
        updateBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtn1MouseClicked(evt);
            }
        });
        jPanel2.add(updateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1000, 50));

        jPanel1.setBackground(new java.awt.Color(242, 248, 255));

        lblCatererName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblCatererName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCatererName.setText("Caterer Name");

        txtCatererName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblCatererLocation.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblCatererLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCatererLocation.setText("Location");

        txtCatererLocation.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblCatererLocation1.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblCatererLocation1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCatererLocation1.setText("Status");

        drpdwnStatus.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        drpdwnStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Service", "Out of service" }));

        lblCatererAdminUsername.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblCatererAdminUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCatererAdminUsername.setText("Admin Username");

        lblCatererAdminPassword.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblCatererAdminPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCatererAdminPassword.setText("Admin Password");

        lblCatererAdminName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        lblCatererAdminName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCatererAdminName.setText("Admin Name");

        txtCatererAdminUsername.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtCatererAdminPassword.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtCatererAdminName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCatererName)
                    .addComponent(lblCatererLocation)
                    .addComponent(lblCatererLocation1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCatererName)
                    .addComponent(txtCatererLocation)
                    .addComponent(drpdwnStatus, 0, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCatererAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCatererAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCatererAdminUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCatererAdminName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtCatererAdminPassword)
                    .addComponent(txtCatererAdminUsername))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCatererName)
                    .addComponent(txtCatererName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCatererAdminUsername)
                    .addComponent(txtCatererAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCatererLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCatererLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCatererAdminPassword)
                    .addComponent(txtCatererAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCatererAdminName)
                        .addComponent(txtCatererAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(drpdwnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCatererLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1000, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtn1MouseClicked
        // TODO add your handling code here:

        if (checkInputFields(txtCatererName) && checkInputFields(txtCatererAdminName) && checkInputFields(txtCatererAdminUsername) && checkInputFields(txtCatererAdminPassword) && checkInputFields(txtCatererLocation)) {
            if (checkIfCatererNameIsUnique()) {
                FoodCateringService newCaterer = new FoodCateringService(txtCatererName.getText(), new Location(42.338767, -71.087863), true);
                Employee CateringAdmin = new Employee(system,txtCatererAdminName.getText(), txtCatererAdminUsername.getText(), txtCatererAdminPassword.getText(), newCaterer, new FoodCateringServiceAdmin());
                newCaterer.getManagement().setAdmin(CateringAdmin);
                system.getCateringServices().add(newCaterer);
                initializeTable();
                resetFields();
                JOptionPane.showMessageDialog(this, "New Caterer has been added");
                DB4OUtil.storeSystem(system);
            } else {
                JOptionPane.showMessageDialog(this, "Caterer name already exists, try a different name");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for adding a new Caterer");
        }
    }//GEN-LAST:event_addBtn1MouseClicked

    private void updateBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtn1MouseClicked
        // TODO add your handling code here:

        if (checkInputFields(txtCatererName) && checkInputFields(txtCatererAdminUsername) && checkInputFields(txtCatererAdminPassword) && checkInputFields(txtCatererLocation)) {
            if (selectedCateringService != null) {
                for (FoodCateringService cateringService : system.getCateringServices()) {
                    if (selectedCateringService.getName().equals(cateringService.getName())) {
                        cateringService.setName(txtCatererName.getText());
//                       String[] locationData =  txtCatererLocation.getText().split(", ");
//                       cateringService.setLocation(new Location(Double.parseDouble(locationData[0]), Double.parseDouble(locationData[1])));
                        cateringService.setLocation(new Location(42.338767, -71.087863));
                        cateringService.getManagement().getAdmin().getUserAccount().setUsername(txtCatererAdminUsername.getText());
                        cateringService.getManagement().getAdmin().getUserAccount().setPassword(txtCatererAdminPassword.getText());
                        cateringService.getManagement().getAdmin().setName(txtCatererAdminName.getText());
                        cateringService.setStatus(drpdwnStatus.getSelectedIndex()==0);
                        initializeTable();
                        resetFields();
                        JOptionPane.showMessageDialog(this, "Caterer details updated successfully");
                        DB4OUtil.storeSystem(system);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a caterer to update from the table");
            }
        }
    }//GEN-LAST:event_updateBtn1MouseClicked

    public boolean checkInputFields(javax.swing.JTextField txtField, String regex) {
        return txtField.getText() != null && !txtField.getText().isEmpty() && txtField.getText().matches(regex);
    }

    public boolean checkInputFields(javax.swing.JTextField txtField) {
        return txtField.getText() != null && !txtField.getText().isEmpty();
    }

    private void initializeTable() {
        ArrayList<FoodCateringService> catererDetails = system.getCateringServices();
        DefaultTableModel tablemodel = (DefaultTableModel) tblCaterers.getModel();
        tablemodel.setRowCount(0);
        if (catererDetails != null) {
            for (FoodCateringService caterer : catererDetails) {
                if (caterer != null) {
                    Object[] row = new Object[6];
                    row[0] = caterer;
                    row[1] = caterer.getManagement().getAdmin().getName();
                    row[2] = caterer.getManagement().getAdmin().getUserAccount().getUsername();
                    row[3] = caterer.getManagement().getAdmin().getUserAccount().getPassword();
                    row[4] = caterer.getLocation();
                    row[5] = caterer.getStatus() == true ? "In service" : "Out of service";
                    tablemodel.addRow(row);
                }
            }
        }
    }

    private void resetFields() {
        txtCatererLocation.setText("");
        txtCatererAdminUsername.setText("");
        txtCatererAdminPassword.setText("");
        txtCatererName.setText("");
        txtCatererAdminName.setText("");
        drpdwnStatus.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn1;
    private javax.swing.JComboBox<String> drpdwnStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCatererAdminName;
    private javax.swing.JLabel lblCatererAdminPassword;
    private javax.swing.JLabel lblCatererAdminUsername;
    private javax.swing.JLabel lblCatererLocation;
    private javax.swing.JLabel lblCatererLocation1;
    private javax.swing.JLabel lblCatererName;
    private javax.swing.JTable tblCaterers;
    private javax.swing.JTextField txtCatererAdminName;
    private javax.swing.JTextField txtCatererAdminPassword;
    private javax.swing.JTextField txtCatererAdminUsername;
    private javax.swing.JTextField txtCatererLocation;
    private javax.swing.JTextField txtCatererName;
    private javax.swing.JLabel updateBtn1;
    // End of variables declaration//GEN-END:variables

    private boolean checkIfCatererNameIsUnique() {
        if(checkInputFields(txtCatererName))
        for (FoodCateringService cateringService : system.getCateringServices()) {
            if (cateringService.getName().equals(txtCatererName.getText())) {
                return false;
            }
        }
        return true;
    }
}
