/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Prison;

import java.awt.CardLayout;

/**
 *
 * @author udayindukuri
 */
public class PrisonGuardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrisonGuardJPanel
     */
    
    CardLayout cardLayoutPointer;
    
    public PrisonGuardJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGuardWorkArea = new javax.swing.JLabel();
        PrisonGuardjCalendar = new com.toedter.calendar.JCalendar();
        btnSubmitAttendance = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        lblGuardWorkArea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGuardWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuardWorkArea.setText("Prison Guard Work Area");
        lblGuardWorkArea.setOpaque(true);

        btnSubmitAttendance.setText("Submit Attendance");

        btnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrisonGuardjCalendar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGuardWorkArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmitAttendance)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuardWorkArea)
                .addGap(18, 18, 18)
                .addComponent(PrisonGuardjCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmitAttendance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar PrisonGuardjCalendar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSubmitAttendance;
    private javax.swing.JLabel lblGuardWorkArea;
    // End of variables declaration//GEN-END:variables
}
