/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Hospital;

import Model.DB4OUtil.DB4OUtil;
import Model.Employee.Employee;
import Model.Hospital.Hospital;
import Model.Prison.HospitalContract;
import Model.PrisonEcosystem;
import Model.Role.PatientCareTechStaff;
import Model.Role.generalStaff;
import Model.Role.psychologyStaff;
import Model.UserAccountManagement.UserAccount;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thejas
 */
public class HospitalAdminLandingPage extends javax.swing.JPanel {

    JPanel container;
    PrisonEcosystem system;
    Hospital hospital;
    String currDesignation;
    UserAccount account;
    ArrayList<HospitalContract> contractList;

    /**
     * Creates new form InfirmaryAdminLandingPage
     *
     * @param container
     */
    public HospitalAdminLandingPage(JPanel container, UserAccount account, PrisonEcosystem system) {
        initComponents();
        this.container = container;
        this.system = system;
        this.account = account;
        hospital = (Hospital) account.getEnterprise();

        this.contractList = hospital.getManagement().getContract();

        //Disable Approal Button.
        btnApproval.setEnabled(false);

        /*
        //Designation drop down list.
        ArrayList<String> designationDownList = new ArrayList<String>();
        
        designationDownList.add("Patient Care Technician");
        designationDownList.add("General Physician");
        designationDownList.add("Psychologist");
        
        for(String x : designationDownList){
            jComboBox1.addItem(x);
        }
         */
        populateContractListTable(contractList);

        contractListTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                initializeFields();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

        });

    }

    private void initializeFields() {
        int viewselectedRowIndex = contractListTable.getSelectedRow();
        HospitalContract selectedContract = (HospitalContract) contractListTable.getModel().getValueAt(viewselectedRowIndex, 0);

        //Approval Button Enable
        if (selectedContract.getGeneralDocsApproval() && selectedContract.getPatientCareTechApproval() && selectedContract.getPsychologistsApproval()) {
            btnApproval.setEnabled(true);
        } else {
            btnApproval.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageStaffPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblInfirmaryStaffName1 = new javax.swing.JLabel();
        txtInfirmaryStaffName = new javax.swing.JTextField();
        lblDesignation1 = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        lblInfirmaryStaffUsername1 = new javax.swing.JLabel();
        txtInfirmaryStaffUsername = new javax.swing.JTextField();
        lblInfirmaryStaffPassword1 = new javax.swing.JLabel();
        txtInfirmaryStaffPassword = new javax.swing.JTextField();
        btnGeneralPhy = new javax.swing.JButton();
        btnPatientCarTec = new javax.swing.JButton();
        btnPsychologist = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        contractListTable = new javax.swing.JTable();
        btnApproval = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageStaffPanel1.setBackground(new java.awt.Color(255, 255, 255));
        manageStaffPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        manageStaffPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(242, 248, 255));

        lblInfirmaryStaffName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInfirmaryStaffName1.setText("Name");

        lblDesignation1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDesignation1.setText("Designation");

        lblInfirmaryStaffUsername1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInfirmaryStaffUsername1.setText("Username");

        lblInfirmaryStaffPassword1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInfirmaryStaffPassword1.setText("Password");

        btnGeneralPhy.setBackground(new java.awt.Color(244, 208, 129));
        btnGeneralPhy.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        btnGeneralPhy.setText("General Physician");
        btnGeneralPhy.setPreferredSize(new java.awt.Dimension(85, 30));
        btnGeneralPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralPhyActionPerformed(evt);
            }
        });

        btnPatientCarTec.setBackground(new java.awt.Color(244, 208, 129));
        btnPatientCarTec.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        btnPatientCarTec.setText("Patient Care Technician");
        btnPatientCarTec.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPatientCarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientCarTecActionPerformed(evt);
            }
        });

        btnPsychologist.setBackground(new java.awt.Color(244, 208, 129));
        btnPsychologist.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        btnPsychologist.setText("Psychologist");
        btnPsychologist.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPsychologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsychologistActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(120, 168, 255));
        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("   Manage Staff");
        jLabel14.setMaximumSize(new java.awt.Dimension(231, 25));
        jLabel14.setMinimumSize(new java.awt.Dimension(231, 25));
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(231, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblInfirmaryStaffUsername1)
                        .addGap(38, 38, 38)
                        .addComponent(txtInfirmaryStaffUsername))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfirmaryStaffName1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfirmaryStaffPassword1))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInfirmaryStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInfirmaryStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDesignation1)
                        .addGap(24, 24, 24)
                        .addComponent(txtDesignation)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGeneralPhy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPatientCarTec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPsychologist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(177, 177, 177)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblInfirmaryStaffName1)
                            .addComponent(txtInfirmaryStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblDesignation1)
                            .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInfirmaryStaffUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfirmaryStaffUsername1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInfirmaryStaffPassword1)
                            .addComponent(txtInfirmaryStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGeneralPhy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPatientCarTec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPsychologist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        manageStaffPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1110, 270));

        jPanel3.setBackground(new java.awt.Color(242, 248, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(120, 168, 255));
        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("   Approve Contracts");
        jLabel15.setMaximumSize(new java.awt.Dimension(231, 25));
        jLabel15.setMinimumSize(new java.awt.Dimension(231, 25));
        jLabel15.setOpaque(true);
        jLabel15.setPreferredSize(new java.awt.Dimension(231, 25));
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 60));

        contractListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Prison", "General Physician", "General Physician Approval", "Patient Care", "Patient Care Approval", "Psychologist", "Psychologist Approval", "Contract Status"
            }
        ));
        jScrollPane4.setViewportView(contractListTable);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1070, 160));

        btnApproval.setText("Approve");
        btnApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovalActionPerformed(evt);
            }
        });
        jPanel3.add(btnApproval, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 249, 160, 40));

        manageStaffPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 1110, 300));

        add(manageStaffPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1150, 640));

        jLabel7.setBackground(new java.awt.Color(71, 120, 197));
        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("   Hospital Staff Administrator");
        jLabel7.setMaximumSize(new java.awt.Dimension(231, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(231, 25));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(231, 25));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1090, 60));

        jPanel1.setBackground(new java.awt.Color(84, 127, 206));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneralPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralPhyActionPerformed
        // TODO add your handling code here:
        currDesignation = "General Physician";

        if (hospital.getPatientCare().getGeneralStaff() == null || hospital.getPatientCare().getGeneralStaff().getName().isEmpty() || hospital.getPatientCare().getGeneralStaff().getName() == null) {
            JOptionPane.showMessageDialog(this, "Please add " + currDesignation);
            return;
        }

        txtInfirmaryStaffName.setText(hospital.getPatientCare().getGeneralStaff().getName());
        txtInfirmaryStaffPassword.setText(hospital.getPatientCare().getGeneralStaff().getUserAccount().getPassword());
        txtInfirmaryStaffUsername.setText(hospital.getPatientCare().getGeneralStaff().getUserAccount().getUsername());
        txtDesignation.setText(currDesignation);
        txtDesignation.setEnabled(false);
    }//GEN-LAST:event_btnGeneralPhyActionPerformed

    private void btnPatientCarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientCarTecActionPerformed
        // TODO add your handling code here:
        currDesignation = "Patient Care Technician";

        if (hospital.getPatientCare().getPhysiotherapyStaff() == null || hospital.getPatientCare().getPhysiotherapyStaff().getName().isEmpty() || hospital.getPatientCare().getPhysiotherapyStaff().getName() == null) {
            JOptionPane.showMessageDialog(this, "Please add " + currDesignation);
            return;
        }

        txtInfirmaryStaffName.setText(hospital.getPatientCare().getPhysiotherapyStaff().getName());
        txtInfirmaryStaffPassword.setText(hospital.getPatientCare().getPhysiotherapyStaff().getUserAccount().getPassword());
        txtInfirmaryStaffUsername.setText(hospital.getPatientCare().getPhysiotherapyStaff().getUserAccount().getUsername());
        txtDesignation.setText(currDesignation);
        txtDesignation.setEnabled(false);
    }//GEN-LAST:event_btnPatientCarTecActionPerformed

    private void btnPsychologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPsychologistActionPerformed
        // TODO add your handling code here:
        currDesignation = "Psychologist";

        if (hospital.getPatientCare().getPsychologyStaff() == null || hospital.getPatientCare().getPsychologyStaff().getName().isEmpty() || hospital.getPatientCare().getPsychologyStaff().getName() == null) {
            JOptionPane.showMessageDialog(this, "Please add " + currDesignation);
            return;
        }

        txtInfirmaryStaffName.setText(hospital.getPatientCare().getPsychologyStaff().getName());
        txtInfirmaryStaffPassword.setText(hospital.getPatientCare().getPsychologyStaff().getUserAccount().getPassword());
        txtInfirmaryStaffUsername.setText(hospital.getPatientCare().getPsychologyStaff().getUserAccount().getUsername());
        txtDesignation.setText(currDesignation);
        txtDesignation.setEnabled(false);

    }//GEN-LAST:event_btnPsychologistActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (checkInputFields(txtInfirmaryStaffName) && checkInputFields(txtInfirmaryStaffUsername) && checkInputFields(txtInfirmaryStaffPassword)) {
            if(!checkInputFields(txtInfirmaryStaffName, "^[\\p{L} .'-]+$") || !checkInputFields(txtInfirmaryStaffUsername, "^[\\p{L} .'-]+$") || !checkInputFields(txtInfirmaryStaffPassword, "^[\\p{L} .'-]+$")){
                JOptionPane.showMessageDialog(this, "Please enter valid Infirmary Staff details");
                return;
            }
//            if (checkIfCatererNameIsUnique()) {
            Employee newEmployee;

            if (txtDesignation.getText().equals("General Physician")) {
                newEmployee = new Employee(system, txtInfirmaryStaffName.getText(), txtInfirmaryStaffUsername.getText(), txtInfirmaryStaffPassword.getText(), hospital, new generalStaff());
                hospital.getPatientCare().setGeneralStaff(newEmployee);
            } else if (txtDesignation.getText().equals("Patient Care Technician")) {
                newEmployee = new Employee(system, txtInfirmaryStaffName.getText(), txtInfirmaryStaffUsername.getText(), txtInfirmaryStaffPassword.getText(), hospital, new PatientCareTechStaff());
                hospital.getPatientCare().setPhysiotherapyStaff(newEmployee);
            } else if (txtDesignation.getText().equals("Psychologist")) {
                newEmployee = new Employee(system, txtInfirmaryStaffName.getText(), txtInfirmaryStaffUsername.getText(), txtInfirmaryStaffPassword.getText(), hospital, new psychologyStaff());
                hospital.getPatientCare().setPsychologyStaff(newEmployee);
            }

            //initializeStaffTable();
            JOptionPane.showMessageDialog(this, txtDesignation.getText() + " Head Appointed");
            resetFields();
//            } else {
//                JOptionPane.showMessageDialog(this, "Caterer name already exists, try a different name");
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for adding a new Employee");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovalActionPerformed
        // TODO add your handling code here:
        int viewselectedRowIndex = contractListTable.getSelectedRow();
        HospitalContract selectedContract = (HospitalContract) contractListTable.getModel().getValueAt(viewselectedRowIndex, 0);

        selectedContract.setStatus("Approved");

        populateContractListTable(contractList);
        JOptionPane.showMessageDialog(this, "The contract has been apporved");

    }//GEN-LAST:event_btnApprovalActionPerformed

    public boolean checkInputFields(javax.swing.JTextField txtField) {
        return txtField.getText() != null && !txtField.getText().isEmpty();
    }
    
     public boolean checkInputFields(javax.swing.JTextField txtField, String regex) {
        return txtField.getText() != null && !txtField.getText().isEmpty() && txtField.getText().matches(regex);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproval;
    private javax.swing.JButton btnGeneralPhy;
    private javax.swing.JButton btnPatientCarTec;
    private javax.swing.JButton btnPsychologist;
    private javax.swing.JButton btnSave;
    private javax.swing.JTable contractListTable;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDesignation1;
    private javax.swing.JLabel lblInfirmaryStaffName1;
    private javax.swing.JLabel lblInfirmaryStaffPassword1;
    private javax.swing.JLabel lblInfirmaryStaffUsername1;
    private javax.swing.JPanel manageStaffPanel1;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtInfirmaryStaffName;
    private javax.swing.JTextField txtInfirmaryStaffPassword;
    private javax.swing.JTextField txtInfirmaryStaffUsername;
    // End of variables declaration//GEN-END:variables

    private void resetFields() {

        txtInfirmaryStaffName.setText("");
        txtInfirmaryStaffPassword.setText("");
        txtInfirmaryStaffUsername.setText("");
        txtDesignation.setText("");
    }

    private void populateContractListTable(ArrayList<HospitalContract> contractList) {
        DefaultTableModel model = (DefaultTableModel) contractListTable.getModel();
        //delete empty records
        model.setRowCount(0);

        for (HospitalContract hc : contractList) {

            Object[] row = new Object[8];
            row[0] = hc;
            row[1] = hc.getGeneralDocs();
            row[2] = hc.getGeneralDocsApproval() == true ? "Yes" : "No";
            row[3] = hc.getPatientCareTech();
            row[4] = hc.getPatientCareTechApproval() == true ? "Yes" : "No";
            row[5] = hc.getPsychologists();
            row[6] = hc.getPsychologistsApproval() == true ? "Yes" : "No";
            row[7] = hc.getStatus();

            model.addRow(row);
        }
    }

}
