/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Hospital;

import Model.Hospital.Hospital;
import Model.Prison.HospitalContract;
import Model.PrisonEcosystem;
import Model.UserAccountManagement.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thejas
 */
public class HospitalStaffLogin extends javax.swing.JPanel {

    JPanel container;
    CardLayout layout;
    PrisonEcosystem system;
    UserAccount user;
    String Designation;
    Hospital hospital;
    ArrayList<HospitalContract> contractList;

    /**
     * Creates new form InfirmaryStaffLogin
     *
     * @param container
     */
    public HospitalStaffLogin(JPanel container, UserAccount user, PrisonEcosystem system) {
        initComponents();
        this.container = container;
        layout = layout = (CardLayout) container.getLayout();
        this.system = system;
        user = user;
        hospital = (Hospital) user.getEnterprise();
        this.contractList = hospital.getManagement().getContract();

        if (hospital.getPatientCare().getGeneralStaff().getUserAccount().getUsername().equals(user.getUsername())) {
            Designation = "generalDocs";
        }
        if (hospital.getPatientCare().getPhysiotherapyStaff().getUserAccount().getUsername().equals(user.getUsername())) {
            Designation = "patientCareTech";
        }
        if (hospital.getPatientCare().getPsychologyStaff().getUserAccount().getUsername().equals(user.getUsername())) {
            Designation = "psychologists";
        }

        this.contractList = hospital.getManagement().getContract();
        populateContractListTable(contractList);

    }

    private void populateContractListTable(ArrayList<HospitalContract> contractList) {
        DefaultTableModel model = (DefaultTableModel) InfirmaryRequestsTable.getModel();
        //delete empty records
        model.setRowCount(0);

        for (HospitalContract hc : contractList) {

            Object[] row = new Object[4];
            row[0] = hc;

            if (Designation.equals("generalDocs")) {
                row[1] = hc.getGeneralDocs();
                row[2] = hc.getGeneralDocsApproval() == true ? "Yes" : "No";
            } else if (Designation.equals("patientCareTech")) {
                row[1] = hc.getPatientCareTech();
                row[2] = hc.getPatientCareTechApproval() == true ? "Yes" : "No";
            } else if (Designation.equals("psychologists")) {
                row[1] = hc.getPsychologists();
                row[2] = hc.getPsychologistsApproval() == true ? "Yes" : "No";
            }

            row[3] = hc.getStatus();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InfirmaryRequestsTable = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();

        InfirmaryRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Prison", "Requirement", "Approval", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(InfirmaryRequestsTable);

        btnSave.setText("Approve");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int viewselectedRowIndex = InfirmaryRequestsTable.getSelectedRow();

        if (viewselectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row before saving");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) InfirmaryRequestsTable.getModel();
        HospitalContract contractRequest = (HospitalContract) model.getValueAt(viewselectedRowIndex, 0);

        //Change Status
        if (Designation.equals("generalDocs")) {
            contractRequest.setGeneralDocsApproval(Boolean.TRUE);
        }
        if (Designation.equals("patientCareTech")) {
            contractRequest.setPatientCareTechApproval(Boolean.TRUE);
        }
        if (Designation.equals("psychologists")) {
            contractRequest.setPsychologistsApproval(Boolean.TRUE);
        }

        populateContractListTable(contractList);
        JOptionPane.showMessageDialog(this, "Contract has been approved");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InfirmaryRequestsTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
