/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Hospital;

import Model.Employee.Employee;
import Model.Hospital.Hospital;
import Model.PrisonEcosystem;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Thejas
 */
public class HospitalAdminLandingPage extends javax.swing.JPanel {

    JPanel container;
    PrisonEcosystem system;
    Hospital hospital;
    String currDesignation;

    /**
     * Creates new form InfirmaryAdminLandingPage
     * @param container
     */
    public HospitalAdminLandingPage(JPanel container, PrisonEcosystem system) {
        initComponents();
        this.container = container;
        this.system = system;
        
        /*
        //Designation drop down list.
        ArrayList<String> designationDownList = new ArrayList<String>();
        
        designationDownList.add("Patient Care Technician");
        designationDownList.add("General Physician");
        designationDownList.add("Psychologist");
        
        for(String x : designationDownList){
            jComboBox1.addItem(x);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        manageStaffPanel = new javax.swing.JPanel();
        lblInfirmaryStaffName = new javax.swing.JLabel();
        txtInfirmaryStaffName = new javax.swing.JTextField();
        lblInfirmaryStaffUsername = new javax.swing.JLabel();
        txtInfirmaryStaffUsername = new javax.swing.JTextField();
        lblInfirmaryStaffPassword = new javax.swing.JLabel();
        txtInfirmaryStaffPassword = new javax.swing.JTextField();
        btnGeneralPhy = new javax.swing.JButton();
        btnPatientCarTec = new javax.swing.JButton();
        btnPsychologist = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblDesignation = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        manageOrders = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInfirmaryOrders = new javax.swing.JTable();
        btnChangeStatus = new javax.swing.JButton();
        btnAssignHeadPsychologist = new javax.swing.JButton();
        btnAssignHeadGeneralPhysician = new javax.swing.JButton();
        btnAssignHeadPatientCareTechnician = new javax.swing.JButton();
        drpdwnAssignHeadPsychologist = new javax.swing.JComboBox<>();
        drpdwnStatus = new javax.swing.JComboBox<>();
        drpdwnAssignHeadPatientCareTechnician = new javax.swing.JComboBox<>();
        drpdwnAssignHeadGeneralPhysician = new javax.swing.JComboBox<>();

        lblInfirmaryStaffName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInfirmaryStaffName.setText("Name");

        lblInfirmaryStaffUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInfirmaryStaffUsername.setText(" Username");

        lblInfirmaryStaffPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInfirmaryStaffPassword.setText(" Password");

        btnGeneralPhy.setBackground(new java.awt.Color(244, 208, 129));
        btnGeneralPhy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGeneralPhy.setText("General Physician");
        btnGeneralPhy.setPreferredSize(new java.awt.Dimension(85, 30));
        btnGeneralPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralPhyActionPerformed(evt);
            }
        });

        btnPatientCarTec.setBackground(new java.awt.Color(244, 208, 129));
        btnPatientCarTec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPatientCarTec.setText("Patient Care Technician");
        btnPatientCarTec.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPatientCarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientCarTecActionPerformed(evt);
            }
        });

        btnPsychologist.setBackground(new java.awt.Color(244, 208, 129));
        btnPsychologist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPsychologist.setText("Psychologist");
        btnPsychologist.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPsychologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsychologistActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Infirmary Admin Work Area");
        jLabel1.setOpaque(true);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblDesignation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDesignation.setText("Designation");

        javax.swing.GroupLayout manageStaffPanelLayout = new javax.swing.GroupLayout(manageStaffPanel);
        manageStaffPanel.setLayout(manageStaffPanelLayout);
        manageStaffPanelLayout.setHorizontalGroup(
            manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(manageStaffPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageStaffPanelLayout.createSequentialGroup()
                        .addComponent(btnPsychologist, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageStaffPanelLayout.createSequentialGroup()
                        .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(manageStaffPanelLayout.createSequentialGroup()
                                .addComponent(btnGeneralPhy, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPatientCarTec, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manageStaffPanelLayout.createSequentialGroup()
                                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInfirmaryStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(manageStaffPanelLayout.createSequentialGroup()
                                        .addComponent(lblDesignation)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageStaffPanelLayout.createSequentialGroup()
                                        .addComponent(lblInfirmaryStaffPassword)
                                        .addGap(21, 21, 21)
                                        .addComponent(txtInfirmaryStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageStaffPanelLayout.createSequentialGroup()
                                        .addComponent(lblInfirmaryStaffUsername)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtInfirmaryStaffUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(83, 83, 83))
                    .addGroup(manageStaffPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(txtInfirmaryStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        manageStaffPanelLayout.setVerticalGroup(
            manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageStaffPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfirmaryStaffName)
                    .addComponent(txtInfirmaryStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInfirmaryStaffUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfirmaryStaffUsername))
                .addGap(33, 33, 33)
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfirmaryStaffPassword)
                    .addComponent(txtInfirmaryStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesignation)
                    .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeneralPhy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatientCarTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addGap(18, 18, 18)
                .addComponent(btnPsychologist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );

        tblInfirmaryOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Institution Name", "Contract duration", "Types of personel required", "No. Of Patients", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblInfirmaryOrders);

        btnChangeStatus.setBackground(new java.awt.Color(244, 208, 129));
        btnChangeStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangeStatus.setText("Change Status");
        btnChangeStatus.setPreferredSize(new java.awt.Dimension(85, 30));
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });

        btnAssignHeadPsychologist.setBackground(new java.awt.Color(244, 208, 129));
        btnAssignHeadPsychologist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAssignHeadPsychologist.setText("Assign head Psychologist");
        btnAssignHeadPsychologist.setPreferredSize(new java.awt.Dimension(85, 30));
        btnAssignHeadPsychologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignHeadPsychologistActionPerformed(evt);
            }
        });

        btnAssignHeadGeneralPhysician.setBackground(new java.awt.Color(244, 208, 129));
        btnAssignHeadGeneralPhysician.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAssignHeadGeneralPhysician.setText("Assign head General Physician");
        btnAssignHeadGeneralPhysician.setPreferredSize(new java.awt.Dimension(85, 30));
        btnAssignHeadGeneralPhysician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignHeadGeneralPhysicianActionPerformed(evt);
            }
        });

        btnAssignHeadPatientCareTechnician.setBackground(new java.awt.Color(244, 208, 129));
        btnAssignHeadPatientCareTechnician.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAssignHeadPatientCareTechnician.setText("Assign head Patient care technician");
        btnAssignHeadPatientCareTechnician.setPreferredSize(new java.awt.Dimension(85, 30));
        btnAssignHeadPatientCareTechnician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignHeadPatientCareTechnicianActionPerformed(evt);
            }
        });

        drpdwnAssignHeadPsychologist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        drpdwnStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        drpdwnAssignHeadPatientCareTechnician.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        drpdwnAssignHeadGeneralPhysician.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout manageOrdersLayout = new javax.swing.GroupLayout(manageOrders);
        manageOrders.setLayout(manageOrdersLayout);
        manageOrdersLayout.setHorizontalGroup(
            manageOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrdersLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(manageOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAssignHeadGeneralPhysician, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(btnChangeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignHeadPsychologist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignHeadPatientCareTechnician, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manageOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drpdwnStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpdwnAssignHeadPsychologist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpdwnAssignHeadPatientCareTechnician, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpdwnAssignHeadGeneralPhysician, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(manageOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageOrdersLayout.setVerticalGroup(
            manageOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrdersLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(manageOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpdwnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drpdwnAssignHeadGeneralPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignHeadGeneralPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(manageOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignHeadPsychologist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpdwnAssignHeadPsychologist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignHeadPatientCareTechnician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpdwnAssignHeadPatientCareTechnician, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageStaffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(manageStaffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 598, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneralPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralPhyActionPerformed
        // TODO add your handling code here:
        currDesignation = "General Physician";
        
        if(hospital.getPatientCare().getGeneralPhysician().getName().isEmpty() || hospital.getPatientCare().getGeneralPhysician().getName() == null){
            JOptionPane.showMessageDialog(this, "Please add " + currDesignation);
            return;
        }
        
        txtInfirmaryStaffName.setText(hospital.getPatientCare().getGeneralPhysician().getName());
        txtInfirmaryStaffPassword.setText(hospital.getPatientCare().getGeneralPhysician().getUserAccount().getPassword());
        txtInfirmaryStaffUsername.setText(hospital.getPatientCare().getGeneralPhysician().getUserAccount().getUsername());
        txtDesignation.setText(currDesignation);
        txtDesignation.disable();
    }//GEN-LAST:event_btnGeneralPhyActionPerformed

    private void btnPatientCarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientCarTecActionPerformed
        // TODO add your handling code here:
        currDesignation = "Patient Care Technician";
        
        if(hospital.getPatientCare().getPatientCareTechnician().getName().isEmpty() || hospital.getPatientCare().getPatientCareTechnician().getName() == null){
            JOptionPane.showMessageDialog(this, "Please add " + currDesignation);
            return;
        }
        
        txtInfirmaryStaffName.setText(hospital.getPatientCare().getPatientCareTechnician().getName());
        txtInfirmaryStaffPassword.setText(hospital.getPatientCare().getPatientCareTechnician().getUserAccount().getPassword());
        txtInfirmaryStaffUsername.setText(hospital.getPatientCare().getPatientCareTechnician().getUserAccount().getUsername());
        txtDesignation.setText(currDesignation);
        txtDesignation.disable();
    }//GEN-LAST:event_btnPatientCarTecActionPerformed

    private void btnPsychologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPsychologistActionPerformed
        // TODO add your handling code here:
        currDesignation = "Psychologist";
        
        if(hospital.getPatientCare().getPsychologist().getName().isEmpty() || hospital.getPatientCare().getPsychologist().getName() == null){
            JOptionPane.showMessageDialog(this, "Please add " + currDesignation);
            return;
        }
        
        txtInfirmaryStaffName.setText(hospital.getPatientCare().getPsychologist().getName());
        txtInfirmaryStaffPassword.setText(hospital.getPatientCare().getPsychologist().getUserAccount().getPassword());
        txtInfirmaryStaffUsername.setText(hospital.getPatientCare().getPsychologist().getUserAccount().getUsername());
        txtDesignation.setText(currDesignation);
        txtDesignation.disable();

    }//GEN-LAST:event_btnPsychologistActionPerformed

    private void btnAssignHeadGeneralPhysicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignHeadGeneralPhysicianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignHeadGeneralPhysicianActionPerformed

    private void btnAssignHeadPsychologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignHeadPsychologistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignHeadPsychologistActionPerformed

    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeStatusActionPerformed

    private void btnAssignHeadPatientCareTechnicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignHeadPatientCareTechnicianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignHeadPatientCareTechnicianActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (checkInputFields(txtInfirmaryStaffName) && checkInputFields(txtInfirmaryStaffUsername) && checkInputFields(txtInfirmaryStaffPassword)) {
//            if (checkIfCatererNameIsUnique()) {
            Employee newEmployee;
            
            if(txtDesignation.equals("General Physician")){
            newEmployee = new Employee(system, txtInfirmaryStaffName.getText(), txtInfirmaryStaffUsername.getText(), txtInfirmaryStaffPassword.getText(), hospital, new Chef());
            hospital.getPatientCare().setGeneralPhysician(newEmployee);
                }
            else if(txtDesignation.equals("Patient Care Technician")){
            newEmployee = new Employee(system, txtInfirmaryStaffName.getText(), txtInfirmaryStaffUsername.getText(), txtInfirmaryStaffPassword.getText(), hospital, new Chef());
            hospital.getPatientCare().setPatientCareTechnician(newEmployee);
            }
            else if(txtDesignation.equals("Psychologist")){
            newEmployee = new Employee(system, txtInfirmaryStaffName.getText(), txtInfirmaryStaffUsername.getText(), txtInfirmaryStaffPassword.getText(), hospital, new Chef());
            hospital.getPatientCare().setPsychologist(newEmployee);
            }
            
            //initializeStaffTable();
            resetFields();
            JOptionPane.showMessageDialog(this, txtDesignation + " Head Appointed");
//            } else {
//                JOptionPane.showMessageDialog(this, "Caterer name already exists, try a different name");
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for adding a new Employee");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public boolean checkInputFields(javax.swing.JTextField txtField) {
        return txtField.getText() != null && !txtField.getText().isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignHeadGeneralPhysician;
    private javax.swing.JButton btnAssignHeadPatientCareTechnician;
    private javax.swing.JButton btnAssignHeadPsychologist;
    private javax.swing.JButton btnChangeStatus;
    private javax.swing.JButton btnGeneralPhy;
    private javax.swing.JButton btnPatientCarTec;
    private javax.swing.JButton btnPsychologist;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> drpdwnAssignHeadGeneralPhysician;
    private javax.swing.JComboBox<String> drpdwnAssignHeadPatientCareTechnician;
    private javax.swing.JComboBox<String> drpdwnAssignHeadPsychologist;
    private javax.swing.JComboBox<String> drpdwnStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblInfirmaryStaffName;
    private javax.swing.JLabel lblInfirmaryStaffPassword;
    private javax.swing.JLabel lblInfirmaryStaffUsername;
    private javax.swing.JPanel manageOrders;
    private javax.swing.JPanel manageStaffPanel;
    private javax.swing.JTable tblInfirmaryOrders;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtInfirmaryStaffName;
    private javax.swing.JTextField txtInfirmaryStaffPassword;
    private javax.swing.JTextField txtInfirmaryStaffUsername;
    // End of variables declaration//GEN-END:variables

    private void resetFields() {
        
        txtInfirmaryStaffName.setText("");
        txtInfirmaryStaffPassword.setText("");
        txtInfirmaryStaffUsername.setText("");
        txtDesignation.setText("");
    }

}
