/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CriminalJusticeSystem;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Thejas
 */
public class JudicialSystemAdminPanel extends javax.swing.JPanel {
JPanel container;
    /**
     * Creates new form JudicialSystemAdminPanel
     * @param container
     */
    public JudicialSystemAdminPanel(JPanel container) {
        initComponents();
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        CourtManagementPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourts = new javax.swing.JTable();
        lblCourtName = new javax.swing.JLabel();
        txtCourtName = new javax.swing.JTextField();
        lblCourtLocation = new javax.swing.JLabel();
        txtJudicialSystemAdminLocation = new javax.swing.JTextField();
        lblJudgeUsername = new javax.swing.JLabel();
        txtJudgeUsername = new javax.swing.JTextField();
        lblJudgePassword = new javax.swing.JLabel();
        txtJudgePassword = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        PoliceDepartmentManagementPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPoliceDepartments = new javax.swing.JTable();
        lblPoliceDepartmentName = new javax.swing.JLabel();
        txtPoliceDepartmentName = new javax.swing.JTextField();
        lblPoliceDepartmentLocation = new javax.swing.JLabel();
        txtPoliceDepartmentAdminLocation = new javax.swing.JTextField();
        lblPoliceDepartmentAdminUsername = new javax.swing.JLabel();
        txtJudicialSystemAdminUsername1 = new javax.swing.JTextField();
        lblPoliceDepartmentAdminPassword = new javax.swing.JLabel();
        txtPoliceDepartmentAdminPassword = new javax.swing.JTextField();
        btnPoliceDepartmentAdd = new javax.swing.JButton();
        btnPoliceDepartmentDelete = new javax.swing.JButton();
        btnPoliceDepartmentUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 1000));

        jPanel1.setPreferredSize(new java.awt.Dimension(798, 1000));

        tblCourts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Password", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCourts);

        lblCourtName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourtName.setText("Court Name");

        lblCourtLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourtLocation.setText("Location");

        lblJudgeUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJudgeUsername.setText("Judge Username");

        lblJudgePassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJudgePassword.setText("Judge Password");

        btnAdd.setBackground(new java.awt.Color(244, 208, 129));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(85, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(244, 208, 129));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(85, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(244, 208, 129));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(85, 30));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CourtManagementPanelLayout = new javax.swing.GroupLayout(CourtManagementPanel);
        CourtManagementPanel.setLayout(CourtManagementPanelLayout);
        CourtManagementPanelLayout.setHorizontalGroup(
            CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CourtManagementPanelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CourtManagementPanelLayout.createSequentialGroup()
                            .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CourtManagementPanelLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(150, 150, 150)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CourtManagementPanelLayout.createSequentialGroup()
                                    .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CourtManagementPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                            .addComponent(lblCourtLocation))
                                        .addGroup(CourtManagementPanelLayout.createSequentialGroup()
                                            .addGap(0, 49, Short.MAX_VALUE)
                                            .addComponent(lblCourtName)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCourtName)
                                        .addComponent(txtJudicialSystemAdminLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(158, 158, 158)
                                    .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblJudgeUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblJudgePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtJudgeUsername)
                                        .addComponent(txtJudgePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(119, 119, 119)))
                    .addGap(5, 5, 5)))
        );
        CourtManagementPanelLayout.setVerticalGroup(
            CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
            .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CourtManagementPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                    .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CourtManagementPanelLayout.createSequentialGroup()
                            .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCourtName)
                                .addComponent(txtCourtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCourtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtJudicialSystemAdminLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(CourtManagementPanelLayout.createSequentialGroup()
                            .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblJudgeUsername)
                                .addComponent(txtJudgeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblJudgePassword)
                                .addComponent(txtJudgePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(69, 69, 69)
                    .addGroup(CourtManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        tblPoliceDepartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Password", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblPoliceDepartments);

        lblPoliceDepartmentName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPoliceDepartmentName.setText("Name");

        lblPoliceDepartmentLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPoliceDepartmentLocation.setText("Location");

        lblPoliceDepartmentAdminUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPoliceDepartmentAdminUsername.setText("Admin Username");

        lblPoliceDepartmentAdminPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPoliceDepartmentAdminPassword.setText("Admin Password");

        btnPoliceDepartmentAdd.setBackground(new java.awt.Color(244, 208, 129));
        btnPoliceDepartmentAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPoliceDepartmentAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnPoliceDepartmentAdd.setText("Add");
        btnPoliceDepartmentAdd.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPoliceDepartmentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceDepartmentAddActionPerformed(evt);
            }
        });

        btnPoliceDepartmentDelete.setBackground(new java.awt.Color(244, 208, 129));
        btnPoliceDepartmentDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPoliceDepartmentDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnPoliceDepartmentDelete.setText("Delete");
        btnPoliceDepartmentDelete.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPoliceDepartmentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceDepartmentDeleteActionPerformed(evt);
            }
        });

        btnPoliceDepartmentUpdate.setBackground(new java.awt.Color(244, 208, 129));
        btnPoliceDepartmentUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPoliceDepartmentUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnPoliceDepartmentUpdate.setText("Update");
        btnPoliceDepartmentUpdate.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPoliceDepartmentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceDepartmentUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PoliceDepartmentManagementPanelLayout = new javax.swing.GroupLayout(PoliceDepartmentManagementPanel);
        PoliceDepartmentManagementPanel.setLayout(PoliceDepartmentManagementPanelLayout);
        PoliceDepartmentManagementPanelLayout.setHorizontalGroup(
            PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliceDepartmentManagementPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PoliceDepartmentManagementPanelLayout.createSequentialGroup()
                        .addComponent(btnPoliceDepartmentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(btnPoliceDepartmentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197)
                        .addComponent(btnPoliceDepartmentDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PoliceDepartmentManagementPanelLayout.createSequentialGroup()
                        .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPoliceDepartmentLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPoliceDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPoliceDepartmentName)
                            .addComponent(txtPoliceDepartmentAdminLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158)
                        .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPoliceDepartmentAdminUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPoliceDepartmentAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJudicialSystemAdminUsername1)
                            .addComponent(txtPoliceDepartmentAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PoliceDepartmentManagementPanelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane3)
                    .addGap(5, 5, 5)))
        );
        PoliceDepartmentManagementPanelLayout.setVerticalGroup(
            PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliceDepartmentManagementPanelLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PoliceDepartmentManagementPanelLayout.createSequentialGroup()
                        .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPoliceDepartmentName)
                            .addComponent(txtPoliceDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPoliceDepartmentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPoliceDepartmentAdminLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PoliceDepartmentManagementPanelLayout.createSequentialGroup()
                        .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPoliceDepartmentAdminUsername)
                            .addComponent(txtJudicialSystemAdminUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPoliceDepartmentAdminPassword)
                            .addComponent(txtPoliceDepartmentAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPoliceDepartmentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoliceDepartmentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoliceDepartmentDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(PoliceDepartmentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PoliceDepartmentManagementPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(278, Short.MAX_VALUE)))
        );

        btnBack.setBackground(new java.awt.Color(244, 208, 129));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CourtManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PoliceDepartmentManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CourtManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PoliceDepartmentManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPoliceDepartmentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceDepartmentAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoliceDepartmentAddActionPerformed

    private void btnPoliceDepartmentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceDepartmentDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoliceDepartmentDeleteActionPerformed

    private void btnPoliceDepartmentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceDepartmentUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoliceDepartmentUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourtManagementPanel;
    private javax.swing.JPanel PoliceDepartmentManagementPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPoliceDepartmentAdd;
    private javax.swing.JButton btnPoliceDepartmentDelete;
    private javax.swing.JButton btnPoliceDepartmentUpdate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCourtLocation;
    private javax.swing.JLabel lblCourtName;
    private javax.swing.JLabel lblJudgePassword;
    private javax.swing.JLabel lblJudgeUsername;
    private javax.swing.JLabel lblPoliceDepartmentAdminPassword;
    private javax.swing.JLabel lblPoliceDepartmentAdminUsername;
    private javax.swing.JLabel lblPoliceDepartmentLocation;
    private javax.swing.JLabel lblPoliceDepartmentName;
    private javax.swing.JTable tblCourts;
    private javax.swing.JTable tblPoliceDepartments;
    private javax.swing.JTextField txtCourtName;
    private javax.swing.JTextField txtJudgePassword;
    private javax.swing.JTextField txtJudgeUsername;
    private javax.swing.JTextField txtJudicialSystemAdminLocation;
    private javax.swing.JTextField txtJudicialSystemAdminUsername1;
    private javax.swing.JTextField txtPoliceDepartmentAdminLocation;
    private javax.swing.JTextField txtPoliceDepartmentAdminPassword;
    private javax.swing.JTextField txtPoliceDepartmentName;
    // End of variables declaration//GEN-END:variables
}
