/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CriminalJusticeSystem;

import Model.CriminalJusticeSystem.Court;
import Model.CriminalJusticeSystem.CriminalJusticeSystem;
import Model.Employee.Employee;
import Model.PrisonEcosystem;
import Model.CriminalJusticeSystem.Police;
import Model.DB4OUtil.DB4OUtil;
import Model.Role.Judge;
import Model.Role.PoliceAdmin;
import Model.UserAccountManagement.UserAccount;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thejas
 */
public class JudicialSystemAdminPanel extends javax.swing.JPanel {

    JPanel container;
    CardLayout layout;
    PrisonEcosystem system;
    Court selectedCourt;
    UserAccount account;
    CriminalJusticeSystem criminalJusticeSystem;
    ArrayList<Court> courts;
    Police selectedPoliceDepartment;
    ArrayList<Police> policeDepartments;

    /**
     * Creates new form JudicialSystemAdminPanel
     *
     * @param container
     * @param account
     * @param system
     */
    public JudicialSystemAdminPanel(JPanel container, UserAccount account, PrisonEcosystem system) {
        initComponents();
        this.container = container;
        layout = (CardLayout) container.getLayout();
        this.system = system;
        this.account = account;
        criminalJusticeSystem = (CriminalJusticeSystem) account.getEnterprise();
        initializeCourtTable();
        inititalizePoliceDepartmentTable();
        tblCourts.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                initializeCourtFields();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

            private void initializeCourtFields() {
                selectedCourt = (Court) tblCourts.getModel().getValueAt(tblCourts.getSelectedRow(), 0);
                txtCourtName.setText(selectedCourt.getName());
                txtJudgeName.setText(selectedCourt.getJudge().getName());
                txtJudgeUsername.setText(selectedCourt.getJudge().getUserAccount().getUsername());
                txtJudgePassword.setText(selectedCourt.getJudge().getUserAccount().getPassword());
            }
        });
        tblPoliceDepartments.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                initializePoliceDepartmentTable();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

            private void initializePoliceDepartmentTable() {
                selectedPoliceDepartment = (Police) tblPoliceDepartments.getModel().getValueAt(tblPoliceDepartments.getSelectedRow(), 0);
                txtPoliceDepartmentName.setText(selectedPoliceDepartment.getName());
                txtPoliceDepartmentAdminName.setText(selectedPoliceDepartment.getPoliceAdmin().getName());
                txtPolcieDepartmentAdminUsername.setText(selectedPoliceDepartment.getPoliceAdmin().getUserAccount().getUsername());
                txtPoliceDepartmentAdminPassword.setText(selectedPoliceDepartment.getPoliceAdmin().getUserAccount().getUsername());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourts = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPoliceDepartments = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblCourtName = new javax.swing.JLabel();
        txtCourtName = new javax.swing.JTextField();
        txtJudgeName = new javax.swing.JTextField();
        lblJudgeName = new javax.swing.JLabel();
        lblJudgeUsername = new javax.swing.JLabel();
        txtJudgeUsername = new javax.swing.JTextField();
        txtJudgePassword = new javax.swing.JTextField();
        lblJudgePassword = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnPoliceDepartmentAdd = new javax.swing.JButton();
        btnPoliceDepartmentUpdate = new javax.swing.JButton();
        btnPoliceDepartmentDelete = new javax.swing.JButton();
        lblPoliceDepartmentName = new javax.swing.JLabel();
        lblPoliceDepartmentAdminName = new javax.swing.JLabel();
        txtPoliceDepartmentName = new javax.swing.JTextField();
        txtPoliceDepartmentAdminName = new javax.swing.JTextField();
        lblPoliceDepartmentAdminUsername = new javax.swing.JLabel();
        txtPolcieDepartmentAdminUsername = new javax.swing.JTextField();
        txtPoliceDepartmentAdminPassword = new javax.swing.JTextField();
        lblPoliceDepartmentAdminPassword = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(71, 120, 197));
        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("   Criminal Justice System Administrator");
        jLabel7.setMaximumSize(new java.awt.Dimension(231, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(231, 25));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(231, 25));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1090, 60));

        jPanel2.setBackground(new java.awt.Color(84, 127, 206));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        tblCourts.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tblCourts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Court name", "Judge name", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCourts);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1110, 190));

        tblPoliceDepartments.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tblPoliceDepartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department name", "Admin name", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblPoliceDepartments);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1110, 190));

        jPanel1.setBackground(new java.awt.Color(242, 248, 255));

        lblCourtName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblCourtName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourtName.setText("Court Name");

        txtCourtName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtJudgeName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblJudgeName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudgeName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudgeName.setText("Judge Name");

        lblJudgeUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudgeUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudgeUsername.setText("Judge Username");

        txtJudgeUsername.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtJudgePassword.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblJudgePassword.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblJudgePassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJudgePassword.setText("Judge Password");

        btnDelete.setBackground(new java.awt.Color(244, 208, 129));
        btnDelete.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(85, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(244, 208, 129));
        btnUpdate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(85, 30));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(244, 208, 129));
        btnAdd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(85, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudgeName)
                    .addComponent(lblCourtName))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCourtName)
                    .addComponent(txtJudgeName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJudgeUsername)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJudgePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJudgeUsername)
                    .addComponent(txtJudgePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblCourtName)
                            .addComponent(txtCourtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJudgeUsername)
                            .addComponent(txtJudgeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblJudgeName)
                            .addComponent(txtJudgeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJudgePassword)
                            .addComponent(txtJudgePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 1110, 90));

        jPanel3.setBackground(new java.awt.Color(242, 248, 255));

        btnPoliceDepartmentAdd.setBackground(new java.awt.Color(244, 208, 129));
        btnPoliceDepartmentAdd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnPoliceDepartmentAdd.setText("Add");
        btnPoliceDepartmentAdd.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPoliceDepartmentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceDepartmentAddActionPerformed(evt);
            }
        });

        btnPoliceDepartmentUpdate.setBackground(new java.awt.Color(244, 208, 129));
        btnPoliceDepartmentUpdate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnPoliceDepartmentUpdate.setText("Update");
        btnPoliceDepartmentUpdate.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPoliceDepartmentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceDepartmentUpdateActionPerformed(evt);
            }
        });

        btnPoliceDepartmentDelete.setBackground(new java.awt.Color(244, 208, 129));
        btnPoliceDepartmentDelete.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnPoliceDepartmentDelete.setText("Delete");
        btnPoliceDepartmentDelete.setPreferredSize(new java.awt.Dimension(85, 30));
        btnPoliceDepartmentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceDepartmentDeleteActionPerformed(evt);
            }
        });

        lblPoliceDepartmentName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblPoliceDepartmentName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPoliceDepartmentName.setText("Department Name");

        lblPoliceDepartmentAdminName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblPoliceDepartmentAdminName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPoliceDepartmentAdminName.setText("Admin name");

        txtPoliceDepartmentName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtPoliceDepartmentAdminName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblPoliceDepartmentAdminUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblPoliceDepartmentAdminUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPoliceDepartmentAdminUsername.setText("Admin Username");

        txtPolcieDepartmentAdminUsername.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        txtPoliceDepartmentAdminPassword.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblPoliceDepartmentAdminPassword.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblPoliceDepartmentAdminPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPoliceDepartmentAdminPassword.setText("Admin Password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoliceDepartmentName)
                    .addComponent(lblPoliceDepartmentAdminName))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPoliceDepartmentName)
                    .addComponent(txtPoliceDepartmentAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPoliceDepartmentAdminUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPoliceDepartmentAdminPassword))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPolcieDepartmentAdminUsername)
                    .addComponent(txtPoliceDepartmentAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPoliceDepartmentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPoliceDepartmentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPoliceDepartmentDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPoliceDepartmentName)
                            .addComponent(txtPoliceDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPoliceDepartmentAdminUsername)
                            .addComponent(txtPolcieDepartmentAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPoliceDepartmentAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPoliceDepartmentAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPoliceDepartmentAdminPassword)
                            .addComponent(txtPoliceDepartmentAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPoliceDepartmentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPoliceDepartmentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPoliceDepartmentDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 1110, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (checkInputFields(txtCourtName) && checkInputFields(txtJudgeUsername) && checkInputFields(txtJudgePassword)) {
//            if (system.getPrisons().checkIfUsernameIsUnique(txtPrisonName.getText())) {

//            if (checkIfPrisonNameIsUnique()) {
            //String[] locationData =  txtPrisonLocation.getText().split(", ");
//Prison newPrison = new Prison(txtPrisonName.getText(), new Location(Double.parseDouble(locationData[0]), Double.parseDouble(locationData[1])));
            Employee newJudge = new Employee(system, txtJudgeName.getText(), txtJudgeUsername.getText(), txtJudgePassword.getText(), criminalJusticeSystem, new Judge());
            Court newCourt = new Court(newJudge, txtCourtName.getText());
            criminalJusticeSystem.getListOfCourts().add(newCourt);
            initializeCourtTable();
            resetCourtFields();
            JOptionPane.showMessageDialog(this, "New Court has been added");
            DB4OUtil.storeSystem(system);
//            } else {
//                JOptionPane.showMessageDialog(this, "Prison name already exists, try a different name");
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for adding a new Court");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    public boolean checkInputFields(javax.swing.JTextField txtField, String regex) {
        return txtField.getText() != null && !txtField.getText().isEmpty() && txtField.getText().matches(regex);
    }

    public boolean checkInputFields(javax.swing.JTextField txtField) {
        return txtField.getText() != null && !txtField.getText().isEmpty();
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedCourt != null) {
            courts.remove(selectedCourt);
            system.getUserAccountDirectory().deleteUserAccount(selectedCourt.getJudge().getUserAccount());
            initializeCourtTable();
            resetCourtFields();
            JOptionPane.showMessageDialog(this, "Court and Judge details deleted successfully");
            DB4OUtil.storeSystem(system);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a court to delete from the table");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (checkInputFields(txtCourtName) && checkInputFields(txtJudgeUsername) && checkInputFields(txtJudgePassword)) {
            if (selectedCourt != null) {
                for (Court court : courts) {
                    if (selectedCourt.getName().equals(court.getName())) {
                        court.getJudge().setName(txtJudgeName.getText());
                        court.getJudge().getUserAccount().setUsername(txtJudgeUsername.getText());
                        court.getJudge().getUserAccount().setPassword(txtJudgePassword.getText());
                        court.setName(txtCourtName.getText());
                        initializeCourtTable();
                        resetCourtFields();
                        JOptionPane.showMessageDialog(this, "Court and judge details updated successfully");
                        DB4OUtil.storeSystem(system);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a court to update from the table");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for updating the court details");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPoliceDepartmentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceDepartmentAddActionPerformed
        // TODO add your handling code here:
        if (checkInputFields(txtPolcieDepartmentAdminUsername) && checkInputFields(txtPoliceDepartmentAdminName) && checkInputFields(txtPoliceDepartmentAdminPassword) && checkInputFields(txtPoliceDepartmentName)) {
//            if (system.getPrisons().checkIfUsernameIsUnique(txtPrisonName.getText())) {

//            if (checkIfPrisonNameIsUnique()) {
            //String[] locationData =  txtPrisonLocation.getText().split(", ");
//Prison newPrison = new Prison(txtPrisonName.getText(), new Location(Double.parseDouble(locationData[0]), Double.parseDouble(locationData[1])));
            Employee newPoliceAdmin = new Employee(system, txtPoliceDepartmentAdminName.getText(), txtPolcieDepartmentAdminUsername.getText(), txtPoliceDepartmentAdminPassword.getText(), criminalJusticeSystem, new PoliceAdmin());
            Police newPoliceDepartment = new Police(newPoliceAdmin, txtPoliceDepartmentName.getText());
            criminalJusticeSystem.getListOfPolice().add(newPoliceDepartment);
            inititalizePoliceDepartmentTable();
            resetPolcieDepartmentFields();
            JOptionPane.showMessageDialog(this, "New Police department has been added");
            DB4OUtil.storeSystem(system);
//            } else {
//                JOptionPane.showMessageDialog(this, "Prison name already exists, try a different name");
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for adding a new police department");
        }
    }//GEN-LAST:event_btnPoliceDepartmentAddActionPerformed

    private void btnPoliceDepartmentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceDepartmentDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedPoliceDepartment != null) {
            policeDepartments.remove(selectedPoliceDepartment);
            system.getUserAccountDirectory().deleteUserAccount(selectedPoliceDepartment.getPoliceAdmin().getUserAccount());
            inititalizePoliceDepartmentTable();
            resetPolcieDepartmentFields();
            JOptionPane.showMessageDialog(this, "Police department details deleted successfully");
            DB4OUtil.storeSystem(system);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a police department to delete from the table");
        }

    }//GEN-LAST:event_btnPoliceDepartmentDeleteActionPerformed

    private void btnPoliceDepartmentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceDepartmentUpdateActionPerformed
        // TODO add your handling code here:
        if (checkInputFields(txtPolcieDepartmentAdminUsername) && checkInputFields(txtPoliceDepartmentAdminName) && checkInputFields(txtPoliceDepartmentAdminPassword) && checkInputFields(txtPoliceDepartmentName)) {
            if (selectedPoliceDepartment != null) {
                for (Police police : policeDepartments) {
                    if (selectedPoliceDepartment.getName().equals(police.getName())) {
                        police.getPoliceAdmin().setName(txtPoliceDepartmentAdminName.getText());
                        police.getPoliceAdmin().getUserAccount().setUsername(txtPolcieDepartmentAdminUsername.getText());
                        police.getPoliceAdmin().getUserAccount().setPassword(txtPoliceDepartmentAdminPassword.getText());
                        police.setName(txtPoliceDepartmentName.getText());
                        inititalizePoliceDepartmentTable();
                        resetPolcieDepartmentFields();
                        JOptionPane.showMessageDialog(this, "Polcie department and polcie admin details updated successfully");
                        DB4OUtil.storeSystem(system);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a police department to update from the table");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty for updating the police department details");
        }

    }//GEN-LAST:event_btnPoliceDepartmentUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPoliceDepartmentAdd;
    private javax.swing.JButton btnPoliceDepartmentDelete;
    private javax.swing.JButton btnPoliceDepartmentUpdate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCourtName;
    private javax.swing.JLabel lblJudgeName;
    private javax.swing.JLabel lblJudgePassword;
    private javax.swing.JLabel lblJudgeUsername;
    private javax.swing.JLabel lblPoliceDepartmentAdminName;
    private javax.swing.JLabel lblPoliceDepartmentAdminPassword;
    private javax.swing.JLabel lblPoliceDepartmentAdminUsername;
    private javax.swing.JLabel lblPoliceDepartmentName;
    private javax.swing.JTable tblCourts;
    private javax.swing.JTable tblPoliceDepartments;
    private javax.swing.JTextField txtCourtName;
    private javax.swing.JTextField txtJudgeName;
    private javax.swing.JTextField txtJudgePassword;
    private javax.swing.JTextField txtJudgeUsername;
    private javax.swing.JTextField txtPolcieDepartmentAdminUsername;
    private javax.swing.JTextField txtPoliceDepartmentAdminName;
    private javax.swing.JTextField txtPoliceDepartmentAdminPassword;
    private javax.swing.JTextField txtPoliceDepartmentName;
    // End of variables declaration//GEN-END:variables

    private void initializeCourtTable() {
        courts = criminalJusticeSystem.getListOfCourts();
        DefaultTableModel tablemodel = (DefaultTableModel) tblCourts.getModel();
        tablemodel.setRowCount(0);
        if (!courts.isEmpty()) {
            for (Court court : courts) {
                if (court != null) {
                    Object[] row = new Object[4];
                    row[0] = court;
                    row[1] = court.getJudge().getName();
                    row[2] = court.getJudge().getUserAccount().getUsername();
                    row[3] = court.getJudge().getUserAccount().getPassword();
                    tablemodel.addRow(row);
                }
            }
        }
    }

    private void resetCourtFields() {
        txtCourtName.setText("");
        txtJudgeName.setText("");
        txtJudgePassword.setText("");
        txtJudgeUsername.setText("");
    }

    private void inititalizePoliceDepartmentTable() {
        policeDepartments = criminalJusticeSystem.getListOfPolice();
        DefaultTableModel tablemodel = (DefaultTableModel) tblPoliceDepartments.getModel();
        tablemodel.setRowCount(0);
        if (!policeDepartments.isEmpty()) {
            for (Police police : policeDepartments) {
                if (police != null) {
                    Object[] row = new Object[4];
                    row[0] = police;
                    row[1] = police.getPoliceAdmin().getName();
                    row[2] = police.getPoliceAdmin().getUserAccount().getUsername();
                    row[3] = police.getPoliceAdmin().getUserAccount().getPassword();
                    tablemodel.addRow(row);
                }
            }
        }
    }

    private void resetPolcieDepartmentFields() {
        txtPoliceDepartmentName.setText("");
        txtPoliceDepartmentAdminPassword.setText("");
        txtPoliceDepartmentAdminName.setText("");
        txtPolcieDepartmentAdminUsername.setText("");
    }
}
